
configfile: "workflow/config.yml"

# rule all:
#     input:
#         "plot/output.png"

rule download_era5:
    input:
	"/home/centos/.cdsapirc"
    output:
        touch("workflow/logs/2023-01-23_download_era5.done")
    log:
        "workflow/logs/2023-01-23_download_era5.log"
    params:
        lon_min = config['lon_min'],
        lon_max = config['lon_max'],
        lat_min = config['lat_min'],
        lat_max = config['lat_max'],
        date_min = config['date_min'],
        date_max = config['date_max']
    shell:
        """
        sudo docker run \
		-v /home/centos/.cdsapirc:/root/.cdsapirc \
		-v /home/centos/data/download/2023-01-23:/data \
		download-input python download_era5.py \
              		--longitude_min {params.lon_min} \
              		--longitude_max {params.lon_max} \
              		--latitude_min {params.lat_min} \
              		--latitude_max {params.lat_max} \
              		--date_min {params.date_min} \
              		--date_max {params.date_max}
        """

rule download_cmems_physics:
    input:
	"workflow/logs/2023-01-23_download_era5.done"
    output:
        touch("workflow/logs/2023-01-23_download_cmems_physics.done")
    log:
        "workflow/logs/2023-01-23_download_cmems_physics.log" #TODO figure out permissions error with this
    params:
        cmems_uname = config['cmems_uname'],
        cmems_pwd = config['cmems_pwd'],
        lon_min = config['lon_min'],
        lon_max = config['lon_max'],
        lat_min = config['lat_min'],
        lat_max = config['lat_max'],
        date_min = config['date_min'],
        date_max = config['date_max']
    shell:
        """
	sudo docker run \
		-v /home/centos/data/download/2023-01-23:/data \
		download-input python download_cmems_physics.py \
              		--username {params.cmems_uname} \
              		--password {params.cmems_pwd} \
              		--longitude_min {params.lon_min} \
              		--longitude_max {params.lon_max} \
              		--latitude_min {params.lat_min} \
              		--latitude_max {params.lat_max} \
              		--date_min {params.date_min} \
              		--date_max {params.date_max}
        """

rule download_cmems_biogeochemistry:
    input:
	"workflow/logs/2023-01-23_download_era5.done"
	"workflow/logs/2023-01-23_download_cmems_physics.done"
    output:
        touch("workflow/logs/2023-01-23_download_cmems_biogeochemistry.done")
    log:
        "workflow/logs/2023-01-23_download_cmems_biogeochemistry.log"
    params:
        cmems_uname = config['cmems_uname'],
        cmems_pwd = config['cmems_pwd'],
        lon_min = config['lon_min'],
        lon_max = config['lon_max'],
        lat_min = config['lat_min'],
        lat_max = config['lat_max'],
        date_min = config['date_min'],
        date_max = config['date_max']
    shell:
        """
	sudo docker run \
		-v /home/centos/data/download/2023-01-23:/data \
		download-input python download_cmems_biogeochemistry.py \
              		--username {params.cmems_uname} \
              		--password {params.cmems_pwd} \
              		--longitude_min {params.lon_min} \
              		--longitude_max {params.lon_max} \
              		--latitude_min {params.lat_min} \
              		--latitude_max {params.lat_max} \
              		--date_min {params.date_min} \
              		--date_max {params.date_max}
        """

rule preprocess_era5:
    input:
	"workflow/logs/2023-01-23_download_era5.done"
	"workflow/logs/2023-01-23_download_cmems_physics.done"
	"workflow/logs/2023-01-23_download_cmems_biogeochemistry.done"
    output:
        "/home/centos/data/preprocout/2023-01-23/era5_FM.nc"
    log:
        "workflow/logs/2023-01-23_preprocess_era5.log"
    shell:
        """
	sudo docker run \
		-v /home/centos/data/download/2023-01-23/era5:/data/input \
		-v /home/centos/data/preprocout/2023-01-23:/data/output \
		getera ERA5_convert2_FM_and_merge_allVars.py \
              		--input /data/input \
              		--output /data/output
        """

rule cleanup:
    shell:
        "rm -rf data/era5/ data/cmems/"

