configfile: "workflow/config.yml"

rule download_era5:
    input:
        "/home/centos/.cdsapirc"
    output:
        touch("workflow/logs/2023-01-23_download_era5.done")
    log:
        "workflow/logs/2023-01-23_download_era5.log"
    params:
        lon_min = config['lon_min'],
        lon_max = config['lon_max'],
        lat_min = config['lat_min'],
        lat_max = config['lat_max'],
        date_min = config['date_min'],
        date_max = config['date_max']
    shell:
        """
        sudo docker run \
            -v {input}:/root/.cdsapirc \
            -v /home/centos/data/download/2023-01-23:/data \
            download-input python download_era5.py \
                --longitude_min {params.lon_min} \
                --longitude_max {params.lon_max} \
                --latitude_min {params.lat_min} \
                --latitude_max {params.lat_max} \
                --date_min {params.date_min} \
                --date_max {params.date_max}
        """

rule download_cmems_physics:
    input:
        "workflow/logs/2023-01-23_download_era5.done"
    output:
        touch("workflow/logs/2023-01-23_download_cmems_physics.done")
    log:
        "workflow/logs/2023-01-23_download_cmems_physics.log"
    params:
        cmems_uname = config['cmems_uname'],
        cmems_pwd = config['cmems_pwd'],
        lon_min = config['lon_min'],
        lon_max = config['lon_max'],
        lat_min = config['lat_min'],
        lat_max = config['lat_max'],
        date_min = config['date_min'],
        date_max = config['date_max']
    shell:
        """
        sudo docker run \
            -v /home/centos/data/download/2023-01-23:/data \
            download-input python download_cmems_physics.py \
                --username {params.cmems_uname} \
                --password {params.cmems_pwd} \
                --longitude_min {params.lon_min} \
                --longitude_max {params.lon_max} \
                --latitude_min {params.lat_min} \
                --latitude_max {params.lat_max} \
                --date_min {params.date_min} \
                --date_max {params.date_max}
        """

rule download_cmems_biogeochemistry:
    input:
        "workflow/logs/2023-01-23_download_era5.done",
        "workflow/logs/2023-01-23_download_cmems_physics.done"
    output:
        touch("workflow/logs/2023-01-23_download_cmems_biogeochemistry.done")
    log:
        "workflow/logs/2023-01-23_download_cmems_biogeochemistry.log"
    params:
        cmems_uname = config['cmems_uname'],
        cmems_pwd = config['cmems_pwd'],
        lon_min = config['lon_min'],
        lon_max = config['lon_max'],
        lat_min = config['lat_min'],
        lat_max = config['lat_max'],
        date_min = config['date_min'],
        date_max = config['date_max']
    shell:
        """
        sudo docker run \
            -v /home/centos/data/download/2023-01-23:/data \
            download-input python download_cmems_biogeochemistry.py \
                --username {params.cmems_uname} \
                --password {params.cmems_pwd} \
                --longitude_min {params.lon_min} \
                --longitude_max {params.lon_max} \
                --latitude_min {params.lat_min} \
                --latitude_max {params.lat_max} \
                --date_min {params.date_min} \
                --date_max {params.date_max}
        """

rule preprocess_era5:
    input:
        "workflow/logs/2023-01-23_download_era5.done"
    output:
        touch("workflow/logs/2023-01-23_preprocess_era5.done")
    log:
        "workflow/logs/2023-01-23_preprocess_era5.log"
    shell:
        """
        sudo docker run \
            -v /home/centos/data/download/2023-01-23/era5:/data/input \
            -v /home/centos/data/preprocout/2023-01-23:/data/output \
            getera ERA5_convert2_FM_and_merge_allVars.py \
                --input /data/input \
                --output /data/output
        """

rule create_random_DFMWAQ_folder:
    output:
        touch("workflow/logs/2023-01-23_create_random_DFMWAQ_folder.done")
    shell:
        "sudo mkdir -p /home/centos/data/preprocout/2023-01-23/DFMWAQ_input"

rule preprocess_cmems:
    input:
        "workflow/logs/2023-01-23_create_random_DFMWAQ_folder.done",
        "workflow/logs/2023-01-23_download_cmems_physics.done",
        "workflow/logs/2023-01-23_download_cmems_biogeochemistry.done"
    output:
        touch("workflow/logs/2023-01-23_preprocess_cmems.done")
    log:
        "workflow/logs/2023-01-23_preprocess_cmems.log"
    shell:
        """
        sudo docker run \
            -v /home/centos/data/download/2023-01-23/cmems:/data/input \
            -v /home/centos/use-case-hisea/fm_model:/data/model \
            -v /home/centos/data/preprocout/2023-01-23:/data/output \
            preprocessing boundary.py \
                --interp true \
                --simultaneous true \
                --steric true \
                --input /data/input \
                --model /data/model \
                --output /data/output
        """

rule preprocess_fes2012:
    input:
        "/home/centos/data/download/fes2012/2N2_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/E2_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/J1_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/K1_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/K2_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/L2_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/LA2_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/M2_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/M3_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/M4_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/M6_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/M8_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/MF_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/MKS2_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/MM_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/MN4_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/MS4_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/MSF_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/MTM_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/MU2_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/N2_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/N4_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/NU2_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/O1_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/P1_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/Q1_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/R2_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/S1_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/S2_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/S4_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/SSA_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/T2_FES2012_SLEV.nc",
        "/home/centos/data/download/fes2012/Z0_FES2012_SLEV.nc"
    output:
        touch("workflow/logs/preprocess_fes2012.done")
    log:
        "workflow/logs/preprocess_fes2012.log"
    params:
        lon_min = config['lon_min'],
        lon_max = config['lon_max'],
        lat_min = config['lat_min'],
        lat_max = config['lat_max']
    shell:
        """
         sudo docker run \
             -v /home/centos/data/download/fes2012:/data/input \
             -v /home/centos/use-case-hisea/fm_model:/data/model \
             -v /home/centos/data/preprocout:/data/output \
             preprocessing tide.py \
                 --fespath /data/input \
                 --coords "{params.lon_min}, {params.lon_max}, {params.lat_min}, {params.lat_max}" \
                 --pli south2.pli \
                 --pli east2.pli \
                 --output /data/output \
                 --model /data/model
        """

rule copy_preprocessed_data_to_model_input_folder:
    input:
        "workflow/logs/2023-01-23_preprocess_cmems.done",
        "workflow/logs/2023-01-23_preprocess_era5.done",
        "workflow/logs/preprocess_fes2012.done"
    output:
        touch("workflow/logs/2023-01-23_copy_preprocessed_data_to_model_input_folder.done")
    shell:
        "cp -r \
            /home/centos/data/preprocout/tide_east2.bc \
            /home/centos/data/preprocout/tide_south2.bc \
            /home/centos/data/preprocout/2023-01-23/DFMWAQ_east2_tmp.ext \
            /home/centos/data/preprocout/2023-01-23/DFMWAQ_input \
            /home/centos/data/preprocout/2023-01-23/DFMWAQ_south2_tmp.ext \
            /home/centos/data/preprocout/2023-01-23/Diat_east2.bc \
            /home/centos/data/preprocout/2023-01-23/Diat_south2.bc \
            /home/centos/data/preprocout/2023-01-23/east2.pli \
            /home/centos/data/preprocout/2023-01-23/Green_east2.bc \
            /home/centos/data/preprocout/2023-01-23/Green_south2.bc \
            /home/centos/data/preprocout/2023-01-23/NO3_east2.bc \
            /home/centos/data/preprocout/2023-01-23/NO3_south2.bc \
            /home/centos/data/preprocout/2023-01-23/Opal_east2.bc \
            /home/centos/data/preprocout/2023-01-23/Opal_south2.bc \
            /home/centos/data/preprocout/2023-01-23/OXY_east2.bc \
            /home/centos/data/preprocout/2023-01-23/OXY_south2.bc \
            /home/centos/data/preprocout/2023-01-23/PO4_east2.bc \
            /home/centos/data/preprocout/2023-01-23/PO4_south2.bc \
            /home/centos/data/preprocout/2023-01-23/POC1_east2.bc \
            /home/centos/data/preprocout/2023-01-23/POC1_south2.bc \
            /home/centos/data/preprocout/2023-01-23/PON1_east2.bc \
            /home/centos/data/preprocout/2023-01-23/PON1_south2.bc \
            /home/centos/data/preprocout/2023-01-23/POP1_east2.bc \
            /home/centos/data/preprocout/2023-01-23/POP1_south2.bc \
            /home/centos/data/preprocout/2023-01-23/salinity_east2.bc \
            /home/centos/data/preprocout/2023-01-23/salinity_south2.bc \
            /home/centos/data/preprocout/2023-01-23/Si_east2.bc \
            /home/centos/data/preprocout/2023-01-23/Si_south2.bc \
            /home/centos/data/preprocout/2023-01-23/south2.pli \
            /home/centos/data/preprocout/2023-01-23/steric_east2.bc \
            /home/centos/data/preprocout/2023-01-23/steric_south2.bc \
            /home/centos/data/preprocout/2023-01-23/temperature_east2.bc \
            /home/centos/data/preprocout/2023-01-23/temperature_south2.bc \
            /home/centos/data/preprocout/2023-01-23/uxuy_east2.bc \
            /home/centos/data/preprocout/2023-01-23/uxuy_south2.bc \
            /home/centos/data/preprocout/2023-01-23/era5_FM.nc \
            /home/centos/use-case-hisea/fm_model/input/."

rule run_delft3dfm:
    input: 
        "workflow/logs/preprocess_fes2012.done",
        "workflow/logs/2023-01-23_preprocess_era5.done",
        "workflow/logs/2023-01-23_preprocess_cmems.done",
        "workflow/logs/2023-01-23_copy_preprocessed_data_to_model_input_folder.done"
    output:
        touch("workflow/logs/2023-01-23_run_delft3dfm.done")
    log:
        "workflow/logs/2023-01-23_run_delft3dfm.log"
    shell:
        """
        sudo docker run \
            -v /home/$USER/use-case-hisea/fm_model:/data \
            --shm-size=4gb \
            --ulimit stack=-1 \
            -t deltares/delft3dfm:latest 
        """

rule cleanup_model_input_folder:
    input:
        "workflow/logs/2023-01-23_run_delft3dfm.done"
    output:
        touch("workflow/logs/2023-01-23_cleanup_model_input_folder.done")
    shell:
        "sudo rm -r \
            /home/centos/use-case-hisea/fm_model/input/tide_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/tide_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/DFMWAQ_east2_tmp.ext \
            /home/centos/use-case-hisea/fm_model/input/DFMWAQ_input \
            /home/centos/use-case-hisea/fm_model/input/DFMWAQ_south2_tmp.ext \
            /home/centos/use-case-hisea/fm_model/input/Diat_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/Diat_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/east2.pli \
            /home/centos/use-case-hisea/fm_model/input/Green_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/Green_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/NO3_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/NO3_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/Opal_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/Opal_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/OXY_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/OXY_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/PO4_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/PO4_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/POC1_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/POC1_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/PON1_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/PON1_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/POP1_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/POP1_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/salinity_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/salinity_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/Si_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/Si_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/south2.pli \
            /home/centos/use-case-hisea/fm_model/input/steric_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/steric_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/temperature_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/temperature_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/uxuy_east2.bc \
            /home/centos/use-case-hisea/fm_model/input/uxuy_south2.bc \
            /home/centos/use-case-hisea/fm_model/input/era5_FM.nc" 

rule move_raw_data_to_output_folder:
    input:
        "workflow/logs/2023-01-23_run_delft3dfm.done"
    output:
        touch("workflow/logs/2023-01-23_move_raw_data_to_output_folder.done")
    shell:
        "mkdir -p /home/centos/data/output/2023-01-23/raw && \
         sudo mv \
             /home/centos/use-case-hisea/fm_model/DFM_OUTPUT_tttz_waq/* \
             /home/centos/data/output/2023-01-23/raw/."

rule cleanup_model_folder:
    input:
        "workflow/logs/2023-01-23_run_delft3dfm.done",
        "workflow/logs/2023-01-23_move_raw_data_to_output_folder.done"
    output:
        touch("workflow/logs/2023-01-23_cleanup_model_folder.done")
    shell:
        "sudo rm \
            /home/centos/use-case-hisea/fm_model/DFM_interpreted_idomain_myortho3_net.nc \
            /home/centos/use-case-hisea/fm_model/log*.irlog \
            /home/centos/use-case-hisea/fm_model/myortho3_*_net.nc \
            /home/centos/use-case-hisea/fm_model/tttz_waq_*.cache \
            /home/centos/use-case-hisea/fm_model/tttz_waq_*.mdu \
            /home/centos/use-case-hisea/fm_model/unstruc.dia"

#rule postprocess_raw_data:
    #input:
        #"workflow/logs/2023-01-23_run_delft3dfm.done",
        #"workflow/logs/2023-01-23_move_raw_data_to_output_folder.done"
    #output:
        #touch("2023-01-23_postprocess_raw_data.done")
    #shell:
        #"""
        #sudo docker run \
             #-v /home/centos/data/output/2023-01-23/raw/DFM_OUTPUT_tttz_waq:/data/input \
             #-v /home/centos/data/output/2023-01-23/struct:/data/output \
             #postprocess tttz_waq_0000_map.nc 500 400
        #"""
